# CONFIGURATION

default:
  image: "registry.gitlab.com/tangram-vision-oss/bolster/ci:latest"
  before_script:
    - rustup update stable

stages:
  - test
  - doc
  - build_artifacts

##### ########## ########## ########## ########## #####
# TEST STAGE
# - [PASS REQ] runs all unit tests in the build
# - [PASS REQ] runs a lint checker over every piece of code
test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

lint:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo clippy --all-targets --all-features -- -D warnings

##### ########## ########## ########## ########## #####
# DOC STAGE
# - [PASS OPT] checks for documentation on all relevant pieces of code
# - [PASS REQ] creates documentation pages
doc-check:
  stage: doc
  script:
    - cargo clippy --all-targets --all-features -- -A clippy::all -D clippy::missing_docs_in_private_items
  allow_failure: true

readme-check:
  stage: doc
  variables:
    # Catches and fails on non-zero status
    FF_ENABLE_BASH_EXIT_CODE_CHECK: 1
  script:
    - readme_check.sh --no-badges --no-title --no-indent-headings

pages:
  stage: doc
  # Run this at the same time as test and lint jobs
  # https://docs.gitlab.com/ee/ci/yaml/#needs
  needs: []
  script:
    # Don't include --document-private-items because we only want to show
    # crate-level docs from lib.rs for end-users.
    - cargo doc --no-deps
    - mkdir public
    - cp -r target/doc/* public
    - cp -r assets public/
    - LOWERCASE_PROJECT_NAME=$(echo $CI_PROJECT_NAME | awk '{print tolower($0)}') && echo "<meta http-equiv=refresh content=0;url=$LOWERCASE_PROJECT_NAME>" > public/index.html
  artifacts:
    paths:
      - public
  only:
    - main

##### ########## ########## ########## ########## #####
# ARTIFACTS STAGE
# - [PASS REQ] update our badges on the project page by
#   creating new SVG artifacts in the ci/ folder.
build_badges:
  stage: build_artifacts
  script:
    - rustc --version
    - cargo --version
    - tangram-badge-generator -d $CI_PROJECT_DIR
  artifacts:
    paths:
      - ./ci/*.svg
    when: always
    expire_in: 4 weeks
  only:
    - main
