[package]
name = "bolster"
version = "0.1.0"
authors = ["Greg Schafer <greg.schafer@tangramvision.com>"]
edition = "2018"
publish = false
repository = "https://gitlab.com/tangram-vision/bolster"
readme = "README.md"
description = """
CLI tool for managing Tangram datasets, including upload/download and search/sort/filter.
"""

[dependencies]
better-panic = "0.2.0"
config = "0.10.1"
failure = "0.1.5"
human-panic = "1.0.3"
lazy_static = "1.4"
log = "0.4.11"
rand = "0.7.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"]}
slog = "2.5.2"
slog-async = "2.5.0"
slog-scope = "4.3.0"
slog-stdlog = "4.1.0"
slog-syslog = "0.12.0"
slog-term = "2.6.0"
url = "1.5"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["yaml"]

[dependencies.reqwest]
version = "^0.10"
default-features = false
features = ["json"]

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"

[profile.dev]
opt-level=0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.release]
opt-level=3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.test]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
